const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  // Clear existing posts
  await prisma.post.deleteMany();

  await prisma.post.createMany({
    data: [
      // ── FIND PARTNER ──────────────────────────────────────────────
      {
        type: "FIND_PARTNER",
        title: "Thiếu 1 nam đánh đôi tối nay tại BetaEra",
        area: "Hải Châu",
        location: "BetaEra Badminton – 273 Nguyễn Tri Phương",
        date: "Hôm nay",
        time: "19:00–21:00",
        skillLevel: "TB",
        playersNeeded: 4,
        playersCurrent: 3,
        contactName: "Minh",
        contactPhone: "0905401655",
        notes: "Sân 3, anh em đến trước 18:45 nhé. Có gửi xe miễn phí.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Nhóm đánh đều thứ 3–5, cần thêm 2 người tại Win Win",
        area: "Liên Chiểu",
        location: "Win Win Badminton – 642 Tôn Đức Thắng",
        date: "Thứ 3, 5 hàng tuần",
        time: "17:30–19:30",
        skillLevel: "Y",
        playersNeeded: 6,
        playersCurrent: 4,
        contactName: "Lan",
        contactPhone: "0912345678",
        notes: "Mới chơi cũng được, mọi người vui vẻ giao lưu. SĐT Zalo.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Tìm 2 nữ đánh giao lưu sáng CN tại Trọng Nghĩa",
        area: "Thanh Khê",
        location: "Trọng Nghĩa Badminton 2 – 194 Bế Văn Đàn",
        date: "Chủ nhật",
        time: "07:00–09:00",
        skillLevel: "TBY",
        playersNeeded: 4,
        playersCurrent: 2,
        contactName: "Thu Hà",
        contactPhone: "0762636662",
        notes: "Nhóm nữ, chơi nhẹ nhàng, có ăn sáng sau khi đánh.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Cần 1 người đánh đơn trình độ khá tại Sân Mỹ An",
        area: "Ngũ Hành Sơn",
        location: "Sân Mỹ An – 382 Ngũ Hành Sơn",
        date: "Thứ 7",
        time: "06:00–08:00",
        skillLevel: "K",
        playersNeeded: 2,
        playersCurrent: 1,
        contactName: "Quang",
        contactPhone: "0947553069",
        notes: "Mình trình độ khá, muốn tìm đối thủ ngang sức.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Nhóm 3 người cần thêm 1 nam đánh tứ tại Arena Sơn Trà",
        area: "Sơn Trà",
        location: "Arena 2 – 25 Hồ Hán Thương",
        date: "Tối nay",
        time: "20:00–22:00",
        skillLevel: "TB",
        playersNeeded: 4,
        playersCurrent: 3,
        contactName: "Dũng",
        contactPhone: "0788818585",
        notes: "Đánh tứ vui, không tranh cãi điểm.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Tìm thêm 3 người đánh nhóm cố định mỗi tối thứ 2–4–6",
        area: "Cẩm Lệ",
        location: "Nhà Thi Đấu Hòa Xuân – 01A Dương Loan",
        date: "Thứ 2, 4, 6 hàng tuần",
        time: "18:00–20:00",
        skillLevel: "TBK",
        playersNeeded: 8,
        playersCurrent: 5,
        contactName: "Tuấn",
        contactPhone: "0905403222",
        notes: "Nhóm công sở, sau giờ làm. Chi phí chia đều mỗi người ~30k/buổi.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Cần 2 người đánh buổi trưa tại sân Bưu Điện",
        area: "Hải Châu",
        location: "Sân Cầu Lông Bưu Điện – 50B Nguyễn Du",
        date: "Thứ 2 đến Thứ 6",
        time: "11:30–13:00",
        skillLevel: "ANY",
        playersNeeded: 4,
        playersCurrent: 2,
        contactName: "Nam",
        contactPhone: "0905185548",
        notes: "Buổi trưa thoải mái, mọi trình độ đều được.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Nhóm cần thêm 1 nữ trình độ tốt thi đấu giao hữu",
        area: "Sơn Trà",
        location: "Aurora Sport – Đường số 6, KCN An Đồn",
        date: "Thứ 7",
        time: "15:00–17:00",
        skillLevel: "T",
        playersNeeded: 4,
        playersCurrent: 3,
        contactName: "Linh",
        contactPhone: "0905690899",
        notes: "Giao hữu thân thiện giữa 2 CLB. Mang vợt cá nhân.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Tìm 4 người đánh giải trí tại Icon Badminton tối CN",
        area: "Thanh Khê",
        location: "Icon Badminton – 122 Tôn Đản",
        date: "Chủ nhật",
        time: "19:30–21:30",
        skillLevel: "TB",
        playersNeeded: 4,
        playersCurrent: 0,
        contactName: "Khoa",
        contactPhone: "0905591379",
        notes: "Chỗ mình book sẵn 2 sân, cần đủ 4 người nữa.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "CLB cần thêm thành viên nữ – đánh thứ 4 & CN",
        area: "Ngũ Hành Sơn",
        location: "Index Sport 2 – 81C Lê Văn Hiến",
        date: "Thứ 4 & Chủ nhật",
        time: "06:30–08:30",
        skillLevel: "TBY",
        playersNeeded: 10,
        playersCurrent: 7,
        contactName: "Mai",
        contactPhone: "0981086979",
        notes: "CLB nữ thân thiện, có HLV hướng dẫn mỗi tháng 1 lần.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Cần 1 nam đánh đôi sáng sớm tại TDTT Hải Châu",
        area: "Hải Châu",
        location: "Trung tâm TDTT Hải Châu – 49 Tân An 3",
        date: "Hàng ngày",
        time: "05:30–07:00",
        skillLevel: "TBK",
        playersNeeded: 4,
        playersCurrent: 3,
        contactName: "Hùng",
        contactPhone: "0905806626",
        notes: "Nhóm sáng sớm, đánh trước giờ đi làm. Rất đúng giờ.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Nhóm sinh viên cần thêm 2 người – sân Kỳ Đồng",
        area: "Thanh Khê",
        location: "Sân Kỳ Đồng – Hòa Khê, Thanh Khê",
        date: "Thứ 3, 5, 7",
        time: "16:00–18:00",
        skillLevel: "Y",
        playersNeeded: 6,
        playersCurrent: 4,
        contactName: "Phong",
        contactPhone: "0914823838",
        notes: "Nhóm sinh viên ĐH Đà Nẵng, vui vẻ, giá chia đều ~20k/người.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "FIND_PARTNER",
        title: "Tìm đối thủ đánh đơn trình độ khá–tốt cuối tuần",
        area: "Liên Chiểu",
        location: "Arena Hoàng Văn Thái – 40 Hoàng Văn Thái",
        date: "Thứ 7 & Chủ nhật",
        time: "08:00–10:00",
        skillLevel: "K",
        playersNeeded: 2,
        playersCurrent: 1,
        contactName: "Bảo",
        contactPhone: "0788818585",
        notes: "Mình có thể đặt sân. Cần người chơi đúng trình, không cạnh tranh quá.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },

      // ── COURT / SÂN TRỐNG ─────────────────────────────────────────
      {
        type: "COURT",
        title: "2 sân trống sáng thứ 7 tại Trọng Nghĩa 1",
        area: "Hải Châu",
        location: "Trọng Nghĩa Badminton 1 – 458 Nguyễn Tri Phương",
        date: "Thứ 7",
        time: "08:00–10:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 80000,
        contactName: "Anh Nghĩa",
        contactPhone: "0702365369",
        notes: "Sàn gỗ chất lượng, đèn sáng, có gửi xe. Book trước 1 tiếng.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Sân BetaEra còn 3 slot tối thứ 6 – sàn BWF chuẩn",
        area: "Hải Châu",
        location: "BetaEra Badminton – 273–275 Nguyễn Tri Phương",
        date: "Thứ 6",
        time: "19:00–21:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 120000,
        contactName: "BetaEra",
        contactPhone: "0935665976",
        notes: "16 sân, sàn BWF chống trơn. Cho thuê vợt 30k/cây. Book qua Zalo.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Nhà Thi Đấu Hòa Xuân còn sân tối CN",
        area: "Cẩm Lệ",
        location: "Nhà Thi Đấu Hòa Xuân – 01A Dương Loan",
        date: "Chủ nhật",
        time: "19:00–21:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 90000,
        contactName: "Quản lý",
        contactPhone: "02363624452",
        notes: "3 sân, bãi xe rộng, gần khu đô thị Hòa Xuân. Điều hòa mát.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Win Win Badminton còn 2 sân sáng mai",
        area: "Liên Chiểu",
        location: "Win Win Badminton – 642 Tôn Đức Thắng",
        date: "Ngày mai",
        time: "06:00–08:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 70000,
        contactName: "Anh Thắng",
        contactPhone: "0927990909",
        notes: "4 sân tốt, gần khu CN Hòa Khánh. Giá sáng sớm ưu đãi.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Icon Badminton còn sân giờ vàng tối thứ 5",
        area: "Thanh Khê",
        location: "Icon Badminton – 122 Tôn Đản",
        date: "Thứ 5",
        time: "20:00–22:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 80000,
        contactName: "Icon Sport",
        contactPhone: "0905591379",
        notes: "Sân mới, đèn LED đủ sáng. Có bán nước, không bán đồ ăn.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Arena Sơn Trà còn 1 sân tối thứ 4 giá tốt",
        area: "Sơn Trà",
        location: "Arena 2 – 25 Hồ Hán Thương, Sơn Trà",
        date: "Thứ 4",
        time: "19:30–21:30",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 70000,
        contactName: "Arena Sport",
        contactPhone: "0788818585",
        notes: "Giảm 10k/giờ nếu book trong ngày. Chỉ còn 1 sân.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Sân Mỹ An – 3 sân trống cả ngày Chủ nhật",
        area: "Ngũ Hành Sơn",
        location: "Sân Mỹ An – 382 Ngũ Hành Sơn",
        date: "Chủ nhật",
        time: "06:00–21:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 60000,
        contactName: "Chị Hoa",
        contactPhone: "0947553069",
        notes: "Gần biển Mỹ An, thoáng mát. Giá tốt nhất khu vực.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "TDTT Hải Châu còn sân sáng thứ 2 đến thứ 6",
        area: "Hải Châu",
        location: "Trung tâm TDTT Hải Châu – 49 Tân An 3",
        date: "Thứ 2 – Thứ 6",
        time: "05:00–07:30",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 70000,
        contactName: "Trung tâm",
        contactPhone: "0905806626",
        notes: "7 sân, mở cửa từ 5h. Phù hợp đánh trước giờ đi làm.",
        sourceUrl: "https://www.facebook.com/groups/809551886722490",
        status: "OPEN",
      },
      {
        type: "COURT",
        title: "Hiếu Con Badminton còn 2 sân tối thứ 7",
        area: "Cẩm Lệ",
        location: "Sân Cầu Lông Hiếu Con – 172 Đỗ Quỳ, Hòa Xuân",
        date: "Thứ 7",
        time: "19:00–21:00",
        skillLevel: "ANY",
        playersNeeded: 0,
        playersCurrent: 0,
        pricePerHour: 80000,
        contactName: "Hiếu",
        contactPhone: "0905403222",
        notes: "4 sân mới cải tạo, gần khu dân cư Hòa Xuân. Có WC sạch.",
        sourceUrl: "https://www.facebook.com/groups/danangbadminton",
        status: "OPEN",
      },
    ],
  });

  console.log("Seeded 26 posts (13 find-partner + 8 court).");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
